
export const allUSColleges = [
    { "id": "100654", "name": "Alabama A & M University", "location": "Normal, AL" },
    { "id": "100663", "name": "University of Alabama at Birmingham", "location": "Birmingham, AL" },
    { "id": "100706", "name": "University of Alabama in Huntsville", "location": "Huntsville, AL" },
    { "id": "100724", "name": "Alabama State University", "location": "Montgomery, AL" },
    { "id": "100751", "name": "The University of Alabama", "location": "Tuscaloosa, AL" },
    { "id": "100858", "name": "Auburn University", "location": "Auburn, AL" },
    { "id": "102094", "name": "University of Alaska Fairbanks", "location": "Fairbanks, AK" },
    { "id": "102234", "name": "Arizona State University", "location": "Tempe, AZ" },
    { "id": "104151", "name": "Northern Arizona University", "location": "Flagstaff, AZ" },
    { "id": "104179", "name": "University of Arizona", "location": "Tucson, AZ" },
    { "id": "104467", "name": "Arkansas State University", "location": "Jonesboro, AR" },
    { "id": "104528", "name": "University of Arkansas", "location": "Fayetteville, AR" },
    { "id": "110635", "name": "University of California-Berkeley", "location": "Berkeley, CA" },
    { "id": "110644", "name": "University of California-Davis", "location": "Davis, CA" },
    { "id": "110653", "name": "University of California-Irvine", "location": "Irvine, CA" },
    { "id": "110662", "name": "University of California-Los Angeles", "location": "Los Angeles, CA" },
    { "id": "110680", "name": "University of California-San Diego", "location": "La Jolla, CA" },
    { "id": "110705", "name": "California Institute of Technology", "location": "Pasadena, CA" },
    { "id": "122931", "name": "Stanford University", "location": "Stanford, CA" },
    { "id": "126614", "name": "Colorado State University", "location": "Fort Collins, CO" },
    { "id": "126678", "name": "University of Colorado Boulder", "location": "Boulder, CO" },
    { "id": "129020", "name": "University of Connecticut", "location": "Storrs, CT" },
    { "id": "130794", "name": "Yale University", "location": "New Haven, CT" },
    { "id": "130934", "name": "University of Delaware", "location": "Newark, DE" },
    { "id": "131496", "name": "American University", "location": "Washington, DC" },
    { "id": "131520", "name": "Georgetown University", "location": "Washington, DC" },
    { "id": "131593", "name": "George Washington University", "location": "Washington, DC" },
    { "id": "131645", "name": "Howard University", "location": "Washington, DC" },
    { "id": "133658", "name": "University of Florida", "location": "Gainesville, FL" },
    { "id": "133685", "name": "Florida A&M University", "location": "Tallahassee, FL" },
    { "id": "133755", "name": "Florida Atlantic University", "location": "Boca Raton, FL" },
    { "id": "133889", "name": "Florida International University", "location": "Miami, FL" },
    { "id": "133959", "name": "Florida State University", "location": "Tallahassee, FL" },
    { "id": "135723", "name": "University of Miami", "location": "Coral Gables, FL" },
    { "id": "138558", "name": "University of South Florida", "location": "Tampa, FL" },
    { "id": "139755", "name": "Georgia Institute of Technology", "location": "Atlanta, GA" },
    { "id": "139959", "name": "Georgia State University", "location": "Atlanta, GA" },
    { "id": "139995", "name": "Emory University", "location": "Atlanta, GA" },
    { "id": "140866", "name": "University of Georgia", "location": "Athens, GA" },
    { "id": "141424", "name": "University of Hawaii at Manoa", "location": "Honolulu, HI" },
    { "id": "142247", "name": "Boise State University", "location": "Boise, ID" },
    { "id": "142274", "name": "University of Idaho", "location": "Moscow, ID" },
    { "id": "144005", "name": "University of Chicago", "location": "Chicago, IL" },
    { "id": "145600", "name": "University of Illinois at Urbana-Champaign", "location": "Champaign, IL" },
    { "id": "145637", "name": "University of Illinois at Chicago", "location": "Chicago, IL" },
    { "id": "147767", "name": "Northwestern University", "location": "Evanston, IL" },
    { "id": "149658", "name": "Southern Illinois University Carbondale", "location": "Carbondale, IL" },
    { "id": "150187", "name": "Indiana University-Bloomington", "location": "Bloomington, IN" },
    { "id": "151351", "name": "Purdue University", "location": "West Lafayette, IN" },
    { "id": "152080", "name": "University of Notre Dame", "location": "Notre Dame, IN" },
    { "id": "153242", "name": "Iowa State University", "location": "Ames, IA" },
    { "id": "153604", "name": "University of Iowa", "location": "Iowa City, IA" },
    { "id": "155317", "name": "Kansas State University", "location": "Manhattan, KS" },
    { "id": "155344", "name": "University of Kansas", "location": "Lawrence, KS" },
    { "id": "157289", "name": "University of Kentucky", "location": "Lexington, KY" },
    { "id": "157395", "name": "University of Louisville", "location": "Louisville, KY" },
    { "id": "159391", "name": "Louisiana State University and Agricultural & Mechanical College", "location": "Baton Rouge, LA" },
    { "id": "160755", "name": "Tulane University of Louisiana", "location": "New Orleans, LA" },
    { "id": "161179", "name": "University of Maine", "location": "Orono, ME" },
    { "id": "162928", "name": "Johns Hopkins University", "location": "Baltimore, MD" },
    { "id": "163284", "name": "University of Maryland-College Park", "location": "College Park, MD" },
    { "id": "164988", "name": "Boston College", "location": "Chestnut Hill, MA" },
    { "id": "165015", "name": "Boston University", "location": "Boston, MA" },
    { "id": "165255", "name": "Brandeis University", "location": "Waltham, MA" },
    { "id": "166027", "name": "Harvard University", "location": "Cambridge, MA" },
    { "id": "166683", "name": "Massachusetts Institute of Technology", "location": "Cambridge, MA" },
    { "id": "168148", "name": "Tufts University", "location": "Medford, MA" },
    { "id": "166629", "name": "University of Massachusetts-Amherst", "location": "Amherst, MA" },
    { "id": "170976", "name": "Michigan State University", "location": "East Lansing, MI" },
    { "id": "171100", "name": "University of Michigan-Ann Arbor", "location": "Ann Arbor, MI" },
    { "id": "172018", "name": "Wayne State University", "location": "Detroit, MI" },
    { "id": "174066", "name": "University of Minnesota-Twin Cities", "location": "Minneapolis, MN" },
    { "id": "176082", "name": "Mississippi State University", "location": "Mississippi State, MS" },
    { "id": "176332", "name": "University of Mississippi", "location": "University, MS" },
    { "id": "178396", "name": "University of Missouri-Columbia", "location": "Columbia, MO" },
    { "id": "179867", "name": "Washington University in St Louis", "location": "Saint Louis, MO" },
    { "id": "180424", "name": "Montana State University", "location": "Bozeman, MT" },
    { "id": "180460", "name": "The University of Montana", "location": "Missoula, MT" },
    { "id": "181464", "name": "University of Nebraska-Lincoln", "location": "Lincoln, NE" },
    { "id": "182290", "name": "University of Nevada-Las Vegas", "location": "Las Vegas, NV" },
    { "id": "182360", "name": "University of Nevada-Reno", "location": "Reno, NV" },
    { "id": "182634", "name": "Dartmouth College", "location": "Hanover, NH" },
    { "id": "182786", "name": "University of New Hampshire", "location": "Durham, NH" },
    { "id": "186131", "name": "Princeton University", "location": "Princeton, NJ" },
    { "id": "186380", "name": "Rutgers University-New Brunswick", "location": "New Brunswick, NJ" },
    { "id": "187532", "name": "New Mexico State University", "location": "Las Cruces, NM" },
    { "id": "187967", "name": "University of New Mexico", "location": "Albuquerque, NM" },
    { "id": "189997", "name": "Columbia University in the City of New York", "location": "New York, NY" },
    { "id": "190150", "name": "Cornell University", "location": "Ithaca, NY" },
    { "id": "193900", "name": "New York University", "location": "New York, NY" },
    { "id": "195030", "name": "Rensselaer Polytechnic Institute", "location": "Troy, NY" },
    { "id": "195409", "name": "University of Rochester", "location": "Rochester, NY" },
    { "id": "196088", "name": "Stony Brook University", "location": "Stony Brook, NY" },
    { "id": "196413", "name": "Syracuse University", "location": "Syracuse, NY" },
    { "id": "190415", "name": "University at Buffalo", "location": "Buffalo, NY" },
    { "id": "198419", "name": "Duke University", "location": "Durham, NC" },
    { "id": "199120", "name": "North Carolina State University", "location": "Raleigh, NC" },
    { "id": "199193", "name": "University of North Carolina at Chapel Hill", "location": "Chapel Hill, NC" },
    { "id": "200032", "name": "Wake Forest University", "location": "Winston-Salem, NC" },
    { "id": "200421", "name": "North Dakota State University", "location": "Fargo, ND" },
    { "id": "200500", "name": "University of North Dakota", "location": "Grand Forks, ND" },
    { "id": "201314", "name": "Case Western Reserve University", "location": "Cleveland, OH" },
    { "id": "204796", "name": "Ohio State University", "location": "Columbus, OH" },
    { "id": "204857", "name": "Ohio University", "location": "Athens, OH" },
    { "id": "201885", "name": "University of Cincinnati", "location": "Cincinnati, OH" },
    { "id": "206366", "name": "University of Toledo", "location": "Toledo, OH" },
    { "id": "207388", "name": "Oklahoma State University", "location": "Stillwater, OK" },
    { "id": "207500", "name": "University of Oklahoma", "location": "Norman, OK" },
    { "id": "209541", "name": "Oregon State University", "location": "Corvallis, OR" },
    { "id": "209550", "name": "University of Oregon", "location": "Eugene, OR" },
    { "id": "211440", "name": "Carnegie Mellon University", "location": "Pittsburgh, PA" },
    { "id": "212058", "name": "Drexel University", "location": "Philadelphia, PA" },
    { "id": "215062", "name": "Pennsylvania State University", "location": "University Park, PA" },
    { "id": "215293", "name": "University of Pennsylvania", "location": "Philadelphia, PA" },
    { "id": "215390", "name": "University of Pittsburgh", "location": "Pittsburgh, PA" },
    { "id": "216597", "name": "Temple University", "location": "Philadelphia, PA" },
    { "id": "217156", "name": "Brown University", "location": "Providence, RI" },
    { "id": "217406", "name": "University of Rhode Island", "location": "Kingston, RI" },
    { "id": "217882", "name": "Clemson University", "location": "Clemson, SC" },
    { "id": "218663", "name": "University of South Carolina-Columbia", "location": "Columbia, SC" },
    { "id": "219833", "name": "South Dakota State University", "location": "Brookings, SD" },
    { "id": "219888", "name": "University of South Dakota", "location": "Vermillion, SD" },
    { "id": "221727", "name": "University of Tennessee-Knoxville", "location": "Knoxville, TN" },
    { "id": "222178", "name": "Vanderbilt University", "location": "Nashville, TN" },
    { "id": "222934", "name": "Baylor University", "location": "Waco, TX" },
    { "id": "227757", "name": "Rice University", "location": "Houston, TX" },
    { "id": "228229", "name": "Southern Methodist University", "location": "Dallas, TX" },
    { "id": "228682", "name": "Texas A&M University", "location": "College Station, TX" },
    { "id": "228725", "name": "Texas Christian University", "location": "Fort Worth, TX" },
    { "id": "228770", "name": "Texas Tech University", "location": "Lubbock, TX" },
    { "id": "228877", "name": "University of Houston", "location": "Houston, TX" },
    { "id": "229104", "name": "University of North Texas", "location": "Denton, TX" },
    { "id": "228761", "name": "The University of Texas at Austin", "location": "Austin, TX" },
    { "id": "229997", "name": "Brigham Young University", "location": "Provo, UT" },
    { "id": "230764", "name": "University of Utah", "location": "Salt Lake City, UT" },
    { "id": "231033", "name": "University of Vermont", "location": "Burlington, VT" },
    { "id": "232557", "name": "University of Virginia", "location": "Charlottesville, VA" },
    { "id": "233921", "name": "Virginia Polytechnic Institute and State University", "location": "Blacksburg, VA" },
    { "id": "234030", "name": "Virginia Commonwealth University", "location": "Richmond, VA" },
    { "id": "234076", "name": "George Mason University", "location": "Fairfax, VA" },
    { "id": "236948", "name": "University of Washington-Seattle Campus", "location": "Seattle, WA" },
    { "id": "237011", "name": "Washington State University", "location": "Pullman, WA" },
    { "id": "238032", "name": "West Virginia University", "location": "Morgantown, WV" },
    { "id": "240444", "name": "University of Wisconsin-Madison", "location": "Madison, WI" },
    { "id": "240800", "name": "University of Wyoming", "location": "Laramie, WY" },
    { "id": "198045", "name": "Appalachian State University", "location": "Boone, NC" },
    { "id": "223232", "name": "Binghamton University", "location": "Binghamton, NY" },
    { "id": "128734", "name": "University of Denver", "location": "Denver, CO" },
    { "id": "156985", "name": "Eastern Kentucky University", "location": "Richmond, KY" },
    { "id": "202215", "name": "Cleveland State University", "location": "Cleveland, OH" },
    { "id": "161474", "name": "Bates College", "location": "Lewiston, ME" },
    { "id": "161544", "name": "Bowdoin College", "location": "Brunswick, ME" },
    { "id": "164542", "name": "Amherst College", "location": "Amherst, MA" },
    { "id": "168218", "name": "Williams College", "location": "Williamstown, MA" },
    { "id": "174240", "name": "Carleton College", "location": "Northfield, MN" },
    { "id": "174480", "name": "Macalester College", "location": "Saint Paul, MN" },
    { "id": "216261", "name": "Swarthmore College", "location": "Swarthmore, PA" },
    { "id": "212937", "name": "Haverford College", "location": "Haverford, PA" },
    { "id": "217217", "name": "Bryn Mawr College", "location": "Bryn Mawr, PA" },
    { "id": "194576", "name": "Pomona College", "location": "Claremont, CA" },
    { "id": "112399", "name": "Claremont McKenna College", "location": "Claremont, CA" },
    { "id": "115408", "name": "Harvey Mudd College", "location": "Claremont, CA" },
    { "id": "243744", "name": "Wesleyan University", "location": "Middletown, CT" },
    { "id": "182625", "name": "Middlebury College", "location": "Middlebury, VT" },
    { "id": "197334", "name": "Vassar College", "location": "Poughkeepsie, NY" },
    { "id": "190530", "name": "Colgate University", "location": "Hamilton, NY" },
    { "id": "191515", "name": "Hamilton College", "location": "Clinton, NY" },
    { "id": "198306", "name": "Davidson College", "location": "Davidson, NC" },
    { "id": "153701", "name": "Grinnell College", "location": "Grinnell, IA" },
    { "id": "204592", "name": "Oberlin College", "location": "Oberlin, OH" },
    { "id": "203673", "name": "Kenyon College", "location": "Gambier, OH" },
    { "id": "208858", "name": "Reed College", "location": "Portland, OR" },
    { "id": "127163", "name": "Colorado College", "location": "Colorado Springs, CO" },
    { "id": "100690", "name": "Samford University", "location": "Birmingham, AL" },
    { "id": "105330", "name": "Harding University", "location": "Searcy, AR" },
    { "id": "121493", "name": "Pepperdine University", "location": "Malibu, CA" },
    { "id": "126838", "name": "Regis University", "location": "Denver, CO" },
    { "id": "130697", "name": "Wesleyan College", "location": "Macon, GA" },
    { "id": "149838", "name": "Wheaton College", "location": "Wheaton, IL" },
    { "id": "152866", "name": "Valparaiso University", "location": "Valparaiso, IN" },
    { "id": "153069", "name": "Drake University", "location": "Des Moines, IA" },
    { "id": "156291", "name": "Bellarmine University", "location": "Louisville, KY" },
    { "id": "159230", "name": "Loyola University New Orleans", "location": "New Orleans, LA" },
    { "id": "163016", "name": "Loyola University Maryland", "location": "Baltimore, MD" },
    { "id": "165415", "name": "Clark University", "location": "Worcester, MA" },
    { "id": "169120", "name": "Calvin University", "location": "Grand Rapids, MI" },
    { "id": "173814", "name": "Augsburg University", "location": "Minneapolis, MN" },
    { "id": "176107", "name": "Millsaps College", "location": "Jackson, MS" },
    { "id": "179426", "name": "Saint Louis University", "location": "Saint Louis, MO" },
    { "id": "181295", "name": "Creighton University", "location": "Omaha, NE" },
    { "id": "186098", "name": "Seton Hall University", "location": "South Orange, NJ" },
    { "id": "194017", "name": "Pace University", "location": "New York, NY" },
    { "id": "198544", "name": "Elon University", "location": "Elon, NC" },
    { "id": "206588", "name": "Xavier University", "location": "Cincinnati, OH" },
    { "id": "207607", "name": "University of Tulsa", "location": "Tulsa, OK" },
    { "id": "216560", "name": "Susquehanna University", "location": "Selinsgrove, PA" },
    { "id": "217642", "name": "Providence College", "location": "Providence, RI" },
    { "id": "218087", "name": "Furman University", "location": "Greenville, SC" },
    { "id": "220197", "name": "Belmont University", "location": "Nashville, TN" },
    { "id": "228965", "name": "Trinity University", "location": "San Antonio, TX" },
    { "id": "230953", "name": "Westminster University", "location": "Salt Lake City, UT" },
    { "id": "233703", "name": "University of Richmond", "location": "University of Richmond, VA" },
    { "id": "235651", "name": "Gonzaga University", "location": "Spokane, WA" },
    { "id": "237936", "name": "West Virginia Wesleyan College", "location": "Buckhannon, WV" },
    { "id": "239335", "name": "Marquette University", "location": "Milwaukee, WI" },
    { "id": "110552", "name": "Biola University", "location": "La Mirada, CA" },
    { "id": "111621", "name": "Chapman University", "location": "Orange, CA" },
    { "id": "122533", "name": "Santa Clara University", "location": "Santa Clara, CA" },
    { "id": "123916", "name": "University of San Diego", "location": "San Diego, CA" },
    { "id": "123943", "name": "University of San Francisco", "location": "San Francisco, CA" },
    { "id": "134947", "name": "Rollins College", "location": "Winter Park, FL" },
    { "id": "135159", "name": "Stetson University", "location": "DeLand, FL" },
    { "id": "139658", "name": "Mercer University", "location": "Macon, GA" },
    { "id": "146487", "name": "Loyola University Chicago", "location": "Chicago, IL" },
    { "id": "150338", "name": "Butler University", "location": "Indianapolis, IN" },
    { "id": "165158", "name": "College of the Holy Cross", "location": "Worcester, MA" },
    { "id": "173934", "name": "University of St Thomas", "location": "Saint Paul, MN" },
    { "id": "202052", "name": "University of Dayton", "location": "Dayton, OH" },
    { "id": "216597", "name": "Villanova University", "location": "Villanova, PA" },
    { "id": "220461", "name": "Rhodes College", "location": "Memphis, TN" },
    { "id": "233958", "name": "Washington and Lee University", "location": "Lexington, VA" },
    { "id": "236957", "name": "Seattle University", "location": "Seattle, WA" },
    { "id": "110404", "name": "Art Center College of Design", "location": "Pasadena, CA" },
    { "id": "110598", "name": "California College of the Arts", "location": "San Francisco, CA" },
    { "id": "144933", "name": "School of the Art Institute of Chicago", "location": "Chicago, IL" },
    { "id": "162900", "name": "Maryland Institute College of Art", "location": "Baltimore, MD" },
    { "id": "166367", "name": "Massachusetts College of Art and Design", "location": "Boston, MA" },
    { "id": "194673", "name": "Pratt Institute", "location": "Brooklyn, NY" },
    { "id": "195368", "name": "Rhode Island School of Design", "location": "Providence, RI" },
    { "id": "195508", "name": "Rochester Institute of Technology", "location": "Rochester, NY" },
    { "id": "196574", "name": "School of Visual Arts", "location": "New York, NY" },
    { "id": "139940", "name": "Savannah College of Art and Design", "location": "Savannah, GA" },
    { "id": "129215", "name": "United States Coast Guard Academy", "location": "New London, CT" },
    { "id": "168281", "name": "United States Merchant Marine Academy", "location": "Kings Point, NY" },
    { "id": "197036", "name": "United States Military Academy", "location": "West Point, NY" },
    { "id": "163257", "name": "United States Naval Academy", "location": "Annapolis, MD" },
    { "id": "126829", "name": "United States Air Force Academy", "location": "USAF Academy, CO" }
  ]
