
// Flows will be imported for their side effects in this file.
import './flows/study-planner-flow';
import './flows/quiz-flow';
import './flows/quiz-explanation-flow';
import './flows/roadmap-flow';
import './flows/note-summary-flow';
import './flows/note-to-quiz-flow';
import './flows/note-to-flashcard-flow';
import './flows/mini-course-flow';
import './flows/module-quiz-flow';
import './flows/module-flashcard-flow';
import './flows/chat-title-flow';
import './flows/image-tutoring-flow';
import './flows/text-to-speech-flow';
import './flows/onboarding-course-flow';
import './flows/course-from-url-flow';
import './flows/chapter-content-flow';
import './tools/course-tool';
import './tools/web-scraper-tool';
import './flows/image-analysis-flow';
import './flows/chat-to-note-flow';
import './flows/midterm-exam-flow';
import './flows/module-content-flow';
import './flows/tutor-chat-flow';
import './flows/image-generation-flow';
import './flows/video-generation-flow';
import './flows/podcast-flow';
import './flows/sat-question-flow';
