
'use client';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { UploadCloud, Play, Pause, ChevronLeft, ChevronRight } from 'lucide-react';
import Link from 'next/link';

export default function LearningLabPage() {
  // Mock data - in a real app, this would come from state management
  const courseTitle = "Introduction to Astrophysics";
  const progress = 45;
  const currentModule = "Stellar Evolution";

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Learning Lab</h1>
        <p className="text-muted-foreground">
          Your personalized learning environment, generated by AI.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Now Learning: {courseTitle}</CardTitle>
          <CardDescription>
            A mini-course generated from your uploaded materials, tailored to your learning style.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-center justify-between">
            <span className="text-sm font-medium">Overall Progress</span>
            <span className="text-sm font-medium">{progress}%</span>
          </div>
          <Progress value={progress} />
        </CardContent>
      </Card>
      
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="md:col-span-2">
            <Card className="h-full">
                <CardHeader>
                    <CardTitle>Current Module: {currentModule}</CardTitle>
                    <CardDescription>Engage with the content below. The format is adapted to your learning style.</CardDescription>
                </CardHeader>
                 <CardContent>
                    {/* Placeholder for dynamic content based on learning style */}
                    <div className="bg-muted h-96 rounded-lg flex items-center justify-center text-muted-foreground">
                        <p>Interactive Content Area (e.g., Video, Quiz, Diagram)</p>
                    </div>
                </CardContent>
            </Card>
        </div>
        <div className="space-y-6">
             <Card>
                <CardHeader>
                    <CardTitle>Controls</CardTitle>
                </CardHeader>
                <CardContent className="flex items-center justify-around">
                    <Button variant="outline" size="icon"><ChevronLeft /></Button>
                    <Button size="icon" className="h-16 w-16"><Play className="h-8 w-8"/></Button>
                    <Button variant="outline" size="icon"><ChevronRight /></Button>
                </CardContent>
             </Card>
             <Card>
                <CardHeader>
                    <CardTitle>Upload Materials</CardTitle>
                    <CardDescription>Add new documents to generate or update your course.</CardDescription>
                </CardHeader>
                <CardContent>
                    <Link href="/dashboard/upload" className="w-full">
                        <Button className="w-full">
                            <UploadCloud className="mr-2 h-4 w-4"/> Upload
                        </Button>
                    </Link>
                </CardContent>
             </Card>
        </div>
      </div>
    </div>
  );
}
